### PR TITLE
ignore me

### PR DESCRIPTION
**Pull request by Distortions81**

### CODE REVIEW

**Comment by Distortions81** [comment]
merge

**Comment by hmcalister** [comment]
Hi there! I am open to suggestions on this project, please feel free to submit a pull request with your work!

I was wondering why you chose to use time.Sleep and time.Since to check for the next frame over sdl.Delay? Is there some inefficiency I am missing using sdl.Delay?

**Comment by Distortions81** [comment]
The PR was unintentional. I find it odd that is the default. Was just
trying to merge branches on my fork. Sorry about that!

**Comment by Distortions81** [comment]
I used time.Sleep, because it supports nanoseconds and not just milliseconds. 60fps is 16.66666ms

**Comment by Distortions81** [comment]
It is only sleeping the remaining frame time at the end, so that can be a very small number as well.

**Pull request closed without merging**
